/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /**
 *
 * @author koshi
 */


package Formulario;

import claseConectar.conectar;
import com.tienda.modelo.Cliente;
import com.tienda.modelo.CustomModel;

import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.*;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrador
 */
public class IngresoCliente extends javax.swing.JInternalFrame {

    TableModel model;

    /**
     * Creates new form IngresoCliente
     */
    public IngresoCliente() {
        initComponents();
        bloquear();
        cargar("");

    }

    void bloquear() {
        idEntrada.setEnabled(false);
        nombreEntrada.setEnabled(false);
        apellidoEntrada.setEnabled(false);
        estadoEntrada.setEnabled(false);
        fotoEntrada.setEnabled(false);
        passwordEntrada.setEnabled(false);
        perfilEntrada.setEnabled(false);
        btnguardar.setEnabled(false);
        btnnuevo.setEnabled(true);
        btncancelar.setEnabled(false);
        btnactualizar.setEnabled(false);

    }

    void limpiar() {
        idEntrada.setText("");
        nombreEntrada.setText("");
        estadoEntrada.setText("");
        perfilEntrada.setText("");
        fotoEntrada.setText("");
        passwordEntrada.setText("");
        apellidoEntrada.setText("");

    }

    void desbloquear() {
        idEntrada.setEnabled(false);
        nombreEntrada.setEnabled(true);
        apellidoEntrada.setEnabled(true);
        estadoEntrada.setEnabled(true);
        fotoEntrada.setEnabled(true);
        passwordEntrada.setEnabled(true);
        perfilEntrada.setEnabled(true);
        btnguardar.setEnabled(true);
        btnnuevo.setEnabled(false);
        btncancelar.setEnabled(true);
        btnactualizar.setEnabled(false);
    }

    void buscar(String valor){
        
        if(valor.equals("")){
            cargar("");
            return;
        }
        
        List<Cliente> lista = new ArrayList<>();
        
        
        CustomModel cm = (CustomModel) tbclientes.getModel();
        List<Cliente> original = cm.getData();
        
        List<Cliente> porNombre = original.stream().filter(item -> item.getNombre().toLowerCase().startsWith(valor.toLowerCase())).collect(Collectors.toList());
        List<Cliente> porApPaterno = original.stream().filter(item -> item.getApellidoPaterno().toLowerCase().startsWith(valor.toLowerCase())).collect(Collectors.toList());
        List<Cliente> porApMaterno = original.stream().filter(item -> item.getApellidoMaterno().toLowerCase().startsWith(valor.toLowerCase())).collect(Collectors.toList());
        
        lista.addAll(porNombre);
        lista.addAll(porApPaterno);
        lista.addAll(porApMaterno);
        
        model = new CustomModel(lista);
        tbclientes.setModel(model);
    }
    
    
    void cargar(String valor) {
        String mostrar = "select * from usuario";
        List<Cliente> lista = new ArrayList<>();

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {

                Cliente c = new Cliente();

                c.setId(rs.getInt("id"));
                c.setNombre(rs.getString("nombre"));
                c.setApellidoPaterno(rs.getString("apellido_paterno"));
                c.setApellidoMaterno(rs.getString("apellido_materno"));
                c.setPassword(rs.getString("password"));
                c.setPerfil(rs.getString("perfil"));
                c.setFoto(rs.getString("foto"));
                c.setStatus(rs.getInt("estado") == 1 ? "VIGENTE" : "NO VIGENTE");

                lista.add(c);
            }

            model = new CustomModel(lista);
            tbclientes.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(IngresoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnmodificar = new javax.swing.JMenuItem();
        mneliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idEntrada = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreEntrada = new javax.swing.JTextField();
        apellidosLabel = new javax.swing.JLabel();
        apellidoEntrada = new javax.swing.JTextField();
        perfilLabel = new javax.swing.JLabel();
        perfilEntrada = new javax.swing.JTextField();
        passwordEntrada = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        fotoEntrada = new javax.swing.JTextField();
        fotoLabel = new javax.swing.JLabel();
        estadoEntrada = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        mnmodificar.setText("Modificar");
        mnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmodificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnmodificar);

        mneliminar.setText("Eliminar");
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mneliminar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRO DE CLIENTES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Cliente"));

        idLabel.setText("ID");

        nombreLabel.setText("Nombre");

        apellidosLabel.setText("Apellidos");

        perfilLabel.setText("Perfil");

        perfilEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilEntradaActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        fotoLabel.setText("Foto");

        estadoLabel.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosLabel)
                            .addComponent(nombreLabel)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 574, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(apellidoEntrada)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perfilLabel)
                            .addComponent(estadoLabel)
                            .addComponent(fotoLabel)
                            .addComponent(passwordLabel))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordEntrada)
                            .addComponent(fotoEntrada)
                            .addComponent(perfilEntrada)
                            .addComponent(estadoEntrada))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfilEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fotoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estadoLabel)
                    .addComponent(estadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnactualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalir)
                .addContainerGap())
        );

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbclientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(tbclientes);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        btnbuscar.setText("Mostrar Todos");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodos(evt);
            }
        });

        jLabel10.setText("BUSCAR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
// TODO add your handling code here:
    try {

        String[] partesApellido = apellidoEntrada.getText().split(" ");
        int status = estadoEntrada.getText().equalsIgnoreCase("vigente") ? 1: 0;

        PreparedStatement pst = cn.prepareStatement("UPDATE usuario SET nombre='"
                + nombreEntrada.getText() + "',apellido_paterno='"
                + partesApellido[0] + "',apellido_materno='"
                + partesApellido[1] + "',perfil='"
                + perfilEntrada.getText() + "',password='"
                + passwordEntrada.getText() + "',foto='"
                + fotoEntrada.getText() + "',estado ='"
                + status + "' WHERE id='" + idEntrada.getText() + "'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro Actualizado con Exito");
        limpiar();
        cargar("");
        bloquear();
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }

}//GEN-LAST:event_btnactualizarActionPerformed

private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnsalirActionPerformed

private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
// TODO add your handling code here:
    desbloquear();
    limpiar();
    nombreEntrada.requestFocus();
}//GEN-LAST:event_btnnuevoActionPerformed

private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
// TODO add your handling code here:
    limpiar();
    bloquear();
    
}//GEN-LAST:event_btncancelarActionPerformed

private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
// TODO add your handling code here:

    String apellidos = apellidoEntrada.getText();
    String[] partesApellido = apellidos.split(" ");
    if(partesApellido.length == 1){
        JOptionPane.showMessageDialog(null, "Debe ingresar Apellido Paterno y Materno");
        return;
    }
    
    
    String sql = "insert into usuario (nombre,usuario,password,perfil,foto,estado,ultimo_login,fecha,apellido_paterno,apellido_materno,vigencia) values (?,?,?,?,?,?,?,?,?,?,?)";

    String id = idEntrada.getText();
    String nombre = nombreEntrada.getText();
    
    String estado = estadoEntrada.getText();
    String password = passwordEntrada.getText();
    String foto = fotoEntrada.getText();
    String perfil = perfilEntrada.getText();

    try {
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, nombre);
        pst.setString(2, "default");
        pst.setString(3, password);
        pst.setString(4, perfil);
        pst.setString(5, foto);
        pst.setInt(6, estado.equalsIgnoreCase("vigente") ? 1 : 0);
        pst.setDate(7, Date.valueOf(LocalDate.now()));
        pst.setDate(8, Date.valueOf(LocalDate.now()));

        

        pst.setString(9, partesApellido[0]);
        pst.setString(10, partesApellido[1]);
        pst.setDate(11, Date.valueOf(LocalDate.now()));

        int n = pst.executeUpdate();
        if (n > 0) {
            JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
            bloquear();
        }
        limpiar();
        cargar("");
    } catch (SQLException ex) {
        Logger.getLogger(IngresoCliente.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_btnguardarActionPerformed

private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
// TODO add your handling code here:
    buscar(txtbuscar.getText());
}//GEN-LAST:event_txtbuscarActionPerformed

private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
// TODO add your handling code here:
    buscar(txtbuscar.getText());
}//GEN-LAST:event_txtbuscarKeyReleased

private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed
// TODO add your handling code here:
    int fila = tbclientes.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "No ha selecionada ninguna fila");
        return;
    }

    CustomModel cm = (CustomModel) tbclientes.getModel();
    Cliente c = cm.getData().get(fila);
    try {
        PreparedStatement pst = cn.prepareStatement("delete from usuario where id ='" + c.getId() + "'");
        pst.executeUpdate();
        limpiar();
        cargar("");        
        bloquear();
    } catch (SQLException ex) {
        Logger.getLogger(IngresoCliente.class.getName()).log(Level.SEVERE, null, ex);
    }


}//GEN-LAST:event_mneliminarActionPerformed

private void mnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmodificarActionPerformed
// TODO add your handling code here:
    int filamodificar = tbclientes.getSelectedRow();
    if (filamodificar == -1) {
        JOptionPane.showMessageDialog(this, "No ha selecionada ninguna fila");
        return;
    }

    desbloquear();
    btnguardar.setEnabled(false);
    btnactualizar.setEnabled(true);
    CustomModel cm = (CustomModel) tbclientes.getModel();
    Cliente c = cm.getData().get(filamodificar);

    idEntrada.setText(String.valueOf(c.getId()));
    nombreEntrada.setText(c.getNombre());
    apellidoEntrada.setText(c.getApellidoPaterno() + " " + c.getApellidoMaterno());
    perfilEntrada.setText(c.getPerfil());
    passwordEntrada.setText(c.getPassword());
    fotoEntrada.setText(c.getFoto());
    estadoEntrada.setText(c.getStatus());
}//GEN-LAST:event_mnmodificarActionPerformed

    private void perfilEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfilEntradaActionPerformed

    private void buscarTodos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodos
       // TODO add your handling code here:
       cargar("");
    }//GEN-LAST:event_buscarTodos


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoEntrada;
    private javax.swing.JLabel apellidosLabel;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField estadoEntrada;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextField fotoEntrada;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JTextField idEntrada;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JMenuItem mnmodificar;
    private javax.swing.JTextField nombreEntrada;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField passwordEntrada;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField perfilEntrada;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
}
